# Generated by Django 2.2 on 2019-04-27 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20190427_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_follows', to='feeds.Profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_follows', to='feeds.Profile'),
        ),
    ]
