# Generated by Django 2.2.1 on 2019-05-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20190428_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='photo',
            field=models.ImageField(blank=True, upload_to='feed_photos'),
        ),
    ]
